version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.6'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bmc
    ports:
      - "3307:3306"
  users-mysql:
    image: users-mysql
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/bmc?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "password"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone