apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-standalone
  name: mysql-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-standalone
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-standalone
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: bmc
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: mysql:5.6
        imagePullPolicy: ""
        name: mysql-standalone
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
