apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: users-mysql
  name: users-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-mysql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: users-mysql
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-standalone:3306/bmc?autoReconnect=true&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        image: users-mysql
        imagePullPolicy: Never
        name: users-mysql
        ports:
        - containerPort: 8086
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
