apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: users-mysql
  name: users-mysql
spec:
  ports:
    - name: "8086"
    port: 8086
    targetPort: 8086
  selector:
    io.kompose.service: users-mysql
status:
  loadBalancer: {}